version: '3.8'

services:
  bot:
    build: .
    container_name: pocket_cfo_bot
    restart: always
    env_file:
      - .env
    volumes:
      - ./pocket_cfo.db:/app/pocket_cfo.db
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
