"""add user_nudges table

Revision ID: 26c663ce6cb6
Revises: 2d8c40050f8a
Create Date: 2026-05-28 18:26:07.134490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26c663ce6cb6'
down_revision: Union[str, Sequence[str], None] = '2d8c40050f8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_nudges',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('nudge_type', sa.String(), nullable=False),
    sa.Column('envelope_id', sa.Integer(), nullable=True),
    sa.Column('datetime_sent', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['envelope_id'], ['envelopes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.telegram_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_nudges')
    # ### end Alembic commands ###
