"""add_is_goal_and_monthly_income

Revision ID: 2d8c40050f8a
Revises: 32706aa18eed
Create Date: 2026-04-14 13:17:38.880205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d8c40050f8a'
down_revision: Union[str, Sequence[str], None] = '32706aa18eed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('envelopes', sa.Column('is_goal', sa.Boolean(), nullable=False, server_default=sa.text('0')))
    op.add_column('users', sa.Column('monthly_income', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'monthly_income')
    op.drop_column('envelopes', 'is_goal')
    # ### end Alembic commands ###
