"""add min_payment to envelopes

Revision ID: c98fd74b3d23
Revises: a0d7a2af58c8
Create Date: 2026-06-01 17:48:10.628532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c98fd74b3d23'
down_revision: Union[str, Sequence[str], None] = 'a0d7a2af58c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('envelopes', sa.Column('min_payment', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('envelopes', 'min_payment')
    # ### end Alembic commands ###
